// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAj4Z9jhwT52X3MfUdKsUTm991p95fEXs',
    appId: '1:670852401318:android:9425bef5fdc0149c004c67',
    messagingSenderId: '670852401318',
    projectId: 'netherlinkadmin',
    storageBucket: 'netherlinkadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDfeYGjjIbtQpXJHJqUl8iARDJe2V0n4',
    appId: '1:670852401318:ios:5d607edeab78971d004c67',
    messagingSenderId: '670852401318',
    projectId: 'netherlinkadmin',
    storageBucket: 'netherlinkadmin.firebasestorage.app',
    iosBundleId: 'net.netherlink.NetherLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRDfeYGjjIbtQpXJHJqUl8iARDJe2V0n4',
    appId: '1:670852401318:ios:5d607edeab78971d004c67',
    messagingSenderId: '670852401318',
    projectId: 'netherlinkadmin',
    storageBucket: 'netherlinkadmin.firebasestorage.app',
    iosBundleId: 'net.netherlink.NetherLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDagxbLCjjUSnEG-KpiPyrXVKSb9i6cxXQ',
    appId: '1:670852401318:web:07f43910010a80e4004c67',
    messagingSenderId: '670852401318',
    projectId: 'netherlinkadmin',
    authDomain: 'netherlinkadmin.firebaseapp.com',
    storageBucket: 'netherlinkadmin.firebasestorage.app',
    measurementId: 'G-JW4FE0PE42',
  );
}
